In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = "pv-italy"

In [4]:
altieri_perm = ["data", "idsito", "kwh", "temperatura_ambiente", "irradiamento", "pressure", "windspeed", "windbearing", "humidity", "dewpoint", "cloudcover", "icon", "altitude", "azimuth" ]
minmax = {
    'idsito': {'min': 1.0, 'max': 41.0}, 
    'idmodel': {'min': 1.0, 'max': 25.0}, 
    'idbrand': {'min': 1.0, 'max': 13.0}, 
    'lat': {'min': 27.227097, 'max': 58.536681}, 
    'lon': {'min': 4.663242, 'max': 24.085558}, 
    'ageinmonths': {'min': 40.0, 'max': 72.0}, 
    'day': {'min': 1.0,'max': 366.0}, 
    'ora': {'min': 2.0, 'max': 20.0}, 
    'temperatura_ambiente': {'min': -14.0, 'max': 52.0}, 
    'irradiamento': {'min': 0.0, 'max': 2285.0}, 
    'pressure': {'min': 0.0, 'max': 1345.43}, 
    'windspeed': {'min': 0.0, 'max': 41.65}, 
    # 'humidity': {'min': 0.12, 'max': 2.0}, 
    'icon': {'min': 1.0, 'max': 13.0}, 
    'dewpoint': {'min': -30.35, 'max': 36.19}, 
    'windbearing': {'min': 0.0, 'max': 467.0}, 
    'tempI':{'min': -1.4845128501381195, 'max': 19.042309822129038}, 
    'irrI': {'min': -26.713624743492094, 'max': 96.67771219990351}, 
    'irrI_PVGIS': {'min': -0.5965064213063707, 'max': 24.097383344906103}, 
    'irrI_PVGIS_MOD': {'min': -1.7676888660163996, 'max': 19.814168501424515}, 
    'irrI_NN': {'min': -2.0807887676644805, 'max': 62.61386349924941}, 
    'pressureI': {'min': -0.0010575817676051176, 'max': 1639.000609384522}, 
    'windspeedI': {'min': -10.028213893385777, 'max': 258.40599262884524}, 
    'humidityI': {'min': -0.8523093365489075, 'max': 19.497844494064836}, 
    'dewpointI': {'min': -7.70993289350107, 'max': 60.88316695617403}, 
    'windbearingI': {'min': -6.872606927446308, 'max':14.560680077466243}, 
    'cloudcoverI': {'min': -5.719429011906163, 'max': 24.516012614925014}, 
    'kwh_previ': {'min': 0.0, 'max': 1.0}, 
    'altitudei': {'min': 0.0, 'max': 1.0}, 
    'azimuthi': {'min': 0.0, 'max': 1.0}, 
    'pcnm1': {'min': -0.498132607, 'max': 0.68728593}, 
    'pcnm2': {'min': -0.3594782449, 'max': 0.5630845122}, 
    'pcnm3': {'min': -0.6760003, 'max': 0.4411391}, 
    'pcnm4': {'min': -0.4941331, 'max': 0.4365071}, 
    'pcnm5': {'min': -0.4073827, 'max': 0.5463372}, 
    'pcnm6': {'min': -0.4998358, 'max': 0.513833}, 
    'pcnm7': {'min': -0.1231909, 'max': 0.9550037}, 
    'pcnm8': {'min': -0.3754114, 'max': 0.5358626}, 
    'pcnm9': {'min': -0.4919784, 'max': 0.4321755}, 
    'pcnm10': {'min': -0.6961635, 'max': 0.4290042}, 
    'pcnm11': {'min': -0.382671, 'max': 0.7887268}, 
    'pcnm12': {'min': -0.7815666, 'max': 0.2637748}, 
    'pcnm13': {'min': -0.591852, 'max': 0.372243}, 
    'pcnm14': {'min': -0.5853832, 'max': 0.6516092}, 
    'pcnm15': {'min': -0.678680524, 'max': 0.504358879},
    # "azimuth": {"min": -180 * 1.3, "max": 144.67 * 1.3},
    # "altitude": {"min": -73.07 * 1.3, "max": 72.95 * 1.3}
    "azimuth": {"min": -234, "max": 189},
    "altitude": {"min": -94, "max": 95}

}
# minmax = {k.lower(): v for k, v in minmax.items()}
print(minmax.keys())

dict_keys(['idsito', 'idmodel', 'idbrand', 'lat', 'lon', 'ageinmonths', 'day', 'ora', 'temperatura_ambiente', 'irradiamento', 'pressure', 'windspeed', 'icon', 'dewpoint', 'windbearing', 'tempI', 'irrI', 'irrI_PVGIS', 'irrI_PVGIS_MOD', 'irrI_NN', 'pressureI', 'windspeedI', 'humidityI', 'dewpointI', 'windbearingI', 'cloudcoverI', 'kwh_previ', 'altitudei', 'azimuthi', 'pcnm1', 'pcnm2', 'pcnm3', 'pcnm4', 'pcnm5', 'pcnm6', 'pcnm7', 'pcnm8', 'pcnm9', 'pcnm10', 'pcnm11', 'pcnm12', 'pcnm13', 'pcnm14', 'pcnm15', 'azimuth', 'altitude'])

In [5]:
data_path = f"../dvc-stages-outputs/{dataset}/raw/{dataset}.parquet"
df = pd.read_parquet(data_path)

In [6]:
df.sort_values(by=["idsito", "data"], inplace=True)
df = df[altieri_perm]
df

,data,idsito,kwh,temperatura_ambiente,irradiamento,pressure,windspeed,windbearing,humidity,dewpoint,cloudcover,icon,altitude,azimuth
0,2012-01-02 02:00:00,0.000,0.000,0.212,0.000,0.000,0.054,0.557,0.82,0.436,0.00,0.083,0.117,0.147
1,2012-01-02 03:00:00,0.000,0.000,0.212,0.000,0.762,0.020,0.441,0.85,0.434,0.11,0.083,0.131,0.207
2,2012-01-02 04:00:00,0.000,0.000,0.212,0.000,0.762,0.086,0.450,0.84,0.431,0.11,0.083,0.175,0.270
3,2012-01-02 05:00:00,0.000,0.000,0.212,0.000,0.762,0.086,0.471,0.70,0.440,0.11,0.083,0.231,0.308
4,2012-01-02 06:00:00,0.000,0.010,0.212,0.002,0.762,0.086,0.493,0.82,0.430,0.11,0.083,0.290,0.335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276483,2014-05-06 16:00:00,0.425,0.025,0.500,0.054,0.758,0.036,0.163,0.56,0.598,0.31,0.000,0.502,0.682
276484,2014-05-06 17:00:00,0.425,0.003,0.485,0.010,0.758,0.046,0.133,0.58,0.596,0.31,0.000,0.737,0.721
276485,2014-05-06 18:00:00,0.425,0.000,0.470,0.000,0.758,0.021,0.191,0.63,0.589,0.31,0.083,0.678,0.749
276486,2014-05-06 19:00:00,0.425,0.000,0.455,0.000,0.758,0.023,0.283,0.73,0.588,0.31,0.083,0.619,0.773
276487,2014-05-06 20:00:00,0.425,0.000,0.439,0.000,0.758,0.039,0.353,0.82,0.609,0.31,0.083,0.559,0.795

In [94]:
from decimal import Decimal, ROUND_HALF_UP

def denormalize_exact(x_norm_str, min_str, max_str, decimals=2):
    x_norm = Decimal(str(x_norm_str))
    min_val = Decimal(str(min_str))
    max_val = Decimal(str(max_str))
    
    # Exact base-10 math
    x_denorm = x_norm * (max_val - min_val) + min_val
    
    # Quantize to target precision
    quantizer = Decimal('1.' + '0' * decimals) if decimals > 0 else Decimal('1')
    return x_denorm.quantize(quantizer, rounding=ROUND_HALF_UP)

In [95]:
for col in df.columns:
    if col in minmax:
        minmax_v = minmax[col]
        # df[col] = df[col] * (minmax_v["max"] - minmax_v["min"]) + minmax_v["min"]
        denormalized_values = df[col].apply(lambda x: denormalize_exact(x, minmax_v["min"], minmax_v["max"], decimals=15))
        df[col] = denormalized_values.astype(float)
    else:
        print(f"Warning: Column '{col}' not found in minmax configuration. Skipping normalization for this column.")
df['kwh'] = df['kwh'] * 1000
df.drop(columns=["icon"], inplace=True)
df.rename(columns={"irradiamento": "irradiance", "temperatura_ambiente": "temperature"}, inplace=True)

Warning: Column 'data' not found in minmax configuration. Skipping normalization for this column.
Warning: Column 'kwh' not found in minmax configuration. Skipping normalization for this column.
Warning: Column 'humidity' not found in minmax configuration. Skipping normalization for this column.
Warning: Column 'cloudcover' not found in minmax configuration. Skipping normalization for this column.

In [ ]:
df

        idsito                data  altitude  azimuth
0          1.0 2012-01-02 02:00:00   -71.887 -171.819
1          1.0 2012-01-02 03:00:00   -69.241 -146.439
2          1.0 2012-01-02 04:00:00   -60.925 -119.790
3          1.0 2012-01-02 05:00:00   -50.341 -103.716
4          1.0 2012-01-02 06:00:00   -39.190  -92.295
...        ...                 ...       ...      ...
276483    18.0 2014-05-06 16:00:00     0.878   54.486
276484    18.0 2014-05-06 17:00:00    45.293   70.983
276485    18.0 2014-05-06 18:00:00    34.142   82.827
276486    18.0 2014-05-06 19:00:00    22.991   92.979
276487    18.0 2014-05-06 20:00:00    11.651  102.285

[276488 rows x 4 columns]

In [ ]:
db_df = pd.read_parquet(f"../dvc-stages-outputs/{dataset}/raw/info_ambientali_corrette_complete.parquet")
db_df.sort_values(by=["site_id", "timestamp"], inplace=True)
db_df = db_df[["timestamp", "site_id", "kwh", "temperature", "irradiance", "pressure", "windspeed", "windbearing", "humidity", "dewpoint", "cloudcover", "altitude", "azimuth" ]]
db_df.drop(columns=["altitude", "azimuth"], inplace=True)
db_df = db_df[(db_df["site_id"] != 8) & (db_df["timestamp"] > pd.Timestamp("2012-01-01 20:00:00"))]
db_df

,timestamp,site_id,kwh,temperature,irradiance,pressure,windspeed,windbearing,humidity,dewpoint,cloudcover
19,2012-01-02 02:00:00,1,0,0,0,0.00,2.24,260.0,0.82,-1.34,0.00
20,2012-01-02 03:00:00,1,0,0,0,1025.41,0.84,206.0,0.85,-1.46,0.11
21,2012-01-02 04:00:00,1,0,0,0,1025.41,3.58,210.0,0.84,-1.69,0.11
22,2012-01-02 05:00:00,1,0,0,0,1025.41,3.58,220.0,0.70,-1.08,0.11
23,2012-01-02 06:00:00,1,10,0,5,1025.16,3.58,230.0,0.82,-1.77,0.11
...,...,...,...,...,...,...,...,...,...,...,...
265900,2014-05-06 16:00:00,18,25,19,123,1020.20,1.49,76.0,0.56,9.41,0.31
265901,2014-05-06 17:00:00,18,3,18,23,1020.20,1.93,62.0,0.58,9.28,0.31
265902,2014-05-06 18:00:00,18,0,17,1,1019.91,0.89,89.0,0.63,8.82,0.31
265903,2014-05-06 19:00:00,18,0,16,1,1019.91,0.95,132.0,0.73,8.77,0.31
265904,2014-05-06 20:00:00,18,0,15,1,1019.91,1.63,165.0,0.82,10.17,0.31

In [100]:
# recover all pair site_id and timestamp that are present in df but not in db_df
mask = ~df.set_index(['data', 'idsito']).index.isin(db_df.set_index(['timestamp', 'site_id']).index)
missing_pairs = df.loc[mask, ['data', 'idsito']]
missing_pairs

                      data  idsito
8683   2013-04-03 02:00:00     1.0
8684   2013-04-03 03:00:00     1.0
8685   2013-04-03 04:00:00     1.0
8686   2013-04-03 05:00:00     1.0
8687   2013-04-03 06:00:00     1.0
...                    ...     ...
268921 2013-04-03 16:00:00    18.0
268922 2013-04-03 17:00:00    18.0
268923 2013-04-03 18:00:00    18.0
268924 2013-04-03 19:00:00    18.0
268925 2013-04-03 20:00:00    18.0

[21166 rows x 2 columns]

In [101]:

def preprocess_missing_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Performs missing data reconstruction, outlier handling (4-sigma), 
    and climatological imputation according to the paper methodology.
    """
    # Create a copy to prevent modifying the original dataframe
    processed_df = df.copy()
    # processed_df['timestamp'] = pd.to_datetime(processed_df['timestamp'])
    
    # Define features to process
    sensor_features = [
        'temperature', 'irradiance', 'pressure', 'windspeed', 
        'humidity', 'dewpoint', 'windbearing', 'cloudcover'
    ]
    target_feature = 'kwh'

    # --- STEP 1: TEMPORAL GRID RECONSTRUCTION ---
    reindexed_slices = []
    
    # Process each site separately to handle different operational timeframes
    for site_id, site_data in processed_df.groupby('site_id'):
        min_date = site_data['timestamp'].min().date()
        max_date = site_data['timestamp'].max().date()
        
        # Generate complete sequence of calendar days
        all_days = pd.date_range(start=min_date, end=max_date, freq='D')
        
        # Generate expected 19 hours (02:00 to 20:00) per day
        expected_grid = []
        for day in all_days:
            for hour in range(2, 21):  # 2 to 20 inclusive
                expected_grid.append(pd.Timestamp(day).replace(hour=hour))
                
        grid_df = pd.DataFrame({'timestamp': expected_grid})
        grid_df['site_id'] = site_id
        
        # Left merge original data onto the complete grid (missing hours become NaN)
        merged = pd.merge(grid_df, site_data, on=['site_id', 'timestamp'], how='left')
        
        # # Forward fill static identifiers (model_id, brand_id)
        # merged['model_id'] = merged['model_id'].ffill().bfill().astype(int)
        # merged['brand_id'] = merged['brand_id'].ffill().bfill().astype(int)
        
        reindexed_slices.append(merged)
        
    df_grid = pd.concat(reindexed_slices, ignore_index=True)

    # # --- STEP 2: OUTLIER DETECTION (4-SIGMA RULE) ---
    # for col in sensor_features:
    #     mean_val = df_grid[col].mean()
    #     std_val = df_grid[col].std()
        
    #     # Define relaxed 4-sigma boundaries
    #     lower_bound = mean_val - 4 * std_val
    #     upper_bound = mean_val + 4 * std_val
        
    #     # Convert outliers to NaN
    #     outliers_mask = (df_grid[col] < lower_bound) | (df_grid[col] > upper_bound)
    #     df_grid.loc[outliers_mask, col] = np.nan

    # --- STEP 3: HIERARCHICAL CLIMATOLOGICAL IMPUTATION ---
    # Extract helper temporal features
    df_grid['year'] = df_grid['timestamp'].dt.year
    df_grid['month'] = df_grid['timestamp'].dt.month
    df_grid['hour'] = df_grid['timestamp'].dt.hour

    # 1. Weather Features: Impute using Site-Year-Month-Hour group averages
    grp_year_month_hour = ['site_id', 'year', 'month', 'hour']
    climatology_year = df_grid.groupby(grp_year_month_hour)[sensor_features].transform('mean')
    for col in sensor_features:
        df_grid[col] = df_grid[col].fillna(climatology_year[col])
        
    # 2. Weather Features Fallback: Impute any remaining NaNs using Site-Month-Hour averages
    grp_month_hour = ['site_id', 'month', 'hour']
    climatology_global = df_grid.groupby(grp_month_hour)[sensor_features].transform('mean')
    for col in sensor_features:
        df_grid[col] = df_grid[col].fillna(climatology_global[col])

    # 3. Target Feature (kWh): Impute using Site-Month-Hour averages (as per paper Section A)
    target_climatology = df_grid.groupby(grp_month_hour)[target_feature].transform('mean')
    df_grid[target_feature] = df_grid[target_feature].fillna(target_climatology)

    # Clean up temporal helpers and return
    df_grid = df_grid.drop(columns=['year', 'month', 'hour'])
    
    # # Interpolate astronomical parameters if missing
    # if 'altitude' in df_grid.columns and 'azimuth' in df_grid.columns:
    #     df_grid['altitude'] = df_grid['altitude'].interpolate(method='linear')
    #     df_grid['azimuth'] = df_grid['azimuth'].interpolate(method='linear')
        
    return df_grid

In [104]:
merged_df = df.merge(missing_pairs, on=['data', 'idsito'], how='inner')[["data", "idsito", "kwh", "humidity", "cloudcover"]]
# merged_df[merged_df["data"] == pd.Timestamp("2013-04-03 03:00:00")]
merged_df

                     data  idsito    kwh  humidity  cloudcover
0     2013-04-03 02:00:00     1.0    0.0      0.86        0.31
1     2013-04-03 03:00:00     1.0   40.0      0.92        0.65
2     2013-04-03 04:00:00     1.0  117.0      0.91        0.31
3     2013-04-03 05:00:00     1.0    7.0      0.91        0.63
4     2013-04-03 06:00:00     1.0   31.0      0.92        0.82
...                   ...     ...    ...       ...         ...
21161 2013-04-03 16:00:00    18.0   27.0      0.71        0.31
21162 2013-04-03 17:00:00    18.0    6.0      0.69        0.31
21163 2013-04-03 18:00:00    18.0    0.0      0.71        0.55
21164 2013-04-03 19:00:00    18.0    0.0      0.78        0.31
21165 2013-04-03 20:00:00    18.0    0.0      0.82        0.31

[21166 rows x 5 columns]